### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by narutosanjiv** [robtweed/qoper8-wt#1]
`Worker Bootstrap Module file written to ./node_modules/qoper8-wt-worker.js
========================================================
qoper8-wt is up and running.  Max worker pool size: 2
========================================================
no available workers
sent qoper8-start message to Worker Thread 1
no available workers
sent qoper8-start message to Worker Thread 2
no available workers
no available workers
no available workers
loading Worker Thread Startup File
loading Worker Thread Startup File

events.js:187
      throw er; // Unhandled 'error' event
      ^
Error: Cannot find module '/Users/kenshin/Documents/workspace/node'
Require stack:
- /Users/kenshin/Documents/workspace/node.js/worker_threads/node_modules/qoper8-wt/lib/worker/proto/init.js
- /Users/kenshin/Documents/workspace/node.js/worker_threads/node_modules/qoper8-wt/lib/qoper8.js
- /Users/kenshin/Documents/workspace/node.js/worker_threads/node_modules/qoper8-wt/index.js
- /Users/kenshin/Documents/workspace/node.js/worker_threads/node_modules/qoper8-wt-worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at workerProcess.init (/Users/kenshin/Documents/workspace/node.js/worker_threads/node_modules/qoper8-wt/lib/worker/proto/init.js:54:27)
    at Object.<anonymous> (/Users/kenshin/Documents/workspace/node.js/worker_threads/node_modules/qoper8-wt-worker.js:6:8)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (internal/worker.js:176:10)
    at Worker.[kOnMessage] (internal/worker.js:186:37)
    at MessagePort.<anonymous> (internal/worker.js:118:57)
    at MessagePort.emit (events.js:210:5)
    at MessagePort.onmessage (internal/worker/io.js:70:8) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kenshin/Documents/workspace/node.js/worker_threads/node_modules/qoper8-wt/lib/worker/proto/init.js',
    '/Users/kenshin/Documents/workspace/node.js/worker_threads/node_modules/qoper8-wt/lib/qoper8.js',
    '/Users/kenshin/Documents/workspace/node.js/worker_threads/node_modules/qoper8-wt/index.js',
    '/Users/kenshin/Documents/workspace/node.js/worker_threads/node_modules/qoper8-wt-worker.js'
  ]
}
*** master received exit event from Worker Thread 1`

**Comment by robtweed** [comment]
You're going to have to provide more information.  What OS / Node.js version, for a start?  Also which example are you referring to and have you modified it (and if so, how)?

Basically the trace above is telling you that it couldn't find this module:
/Users/kenshin/Documents/workspace/node

which I assume is what qoper8-wt has been told is your message handler module?    It's certainly nothing that qoper8-wt would be trying to load itself.

I've just tried the examples on one of my systems and they run just fine, so there's something you've done that is causing it to fail.  Show the actual code you're trying to run and the directory structure you're trying to use to run it with, and I might be able to help
